pipeline:
  backend:
    image: g3rv4/traducir-builder
    commands:
      - mkdir -p app/backend

      - cd Traducir.Api
      - dotnet publish -c Release -f netcoreapp2.0 -o ../app/backend
  frontend:
    image: g3rv4/traducir-builder
    commands:
      - mkdir -p app/frontend

      - cd Traducir.Web
      - cp -r /var/node_modules node_modules
      - npm run build
      - cp -r ./dist/* ../app/frontend/
  release-dev:
    image: g3rv4/traducir-builder
    commands:
      - mkdir ~/.ssh
      - echo -n "$${SSH_KEY}" > /root/.ssh/id_rsa
      - chmod 0600 /root/.ssh/id_rsa
      - git config --global user.name 'Deploy system'
      - git config --global user.email 'gmc+deploy@gmc.uy'
      - ssh-keyscan github.com >> /root/.ssh/known_hosts
      - ls /root/.ssh

      - git clone git@github.com:g3rv4-docker/traducir.git
      - rm -rf traducir/app
      - cp -r app traducir/app
      - cd traducir
      - git checkout dev
      - git add app
      - "git commit -m \"Source update: ${DRONE_COMMIT_SHA}\""
      - git push
    secrets: [ ssh_key ]
    when:
      event: push
      branch: master
  release-prod:
    image: g3rv4/traducir-builder
    commands:
      - mkdir ~/.ssh
      - echo -n "$${SSH_KEY}" > /root/.ssh/id_rsa
      - chmod 0600 /root/.ssh/id_rsa
      - git config --global user.name 'Deploy system'
      - git config --global user.email 'gmc+deploy@gmc.uy'
      - ssh-keyscan github.com >> /root/.ssh/known_hosts
      - ls /root/.ssh

      - git clone git@github.com:g3rv4-docker/traducir.git
      - rm -rf traducir/app
      - cp -r app traducir/app
      - cd traducir
      - git add app
      - "git commit -m \"Source update: ${DRONE_COMMIT_SHA}\""
      - git push
    secrets: [ ssh_key ]
    when:
      event: deployment
