pipeline:
  backend:
    image: g3rv4/transifex-builder
    commands:
      - "mkdir -p app/backend"
      - "cd Traducir.Api"
      - "dotnet publish -c Release -f netcoreapp2.0 -o ../app/backend"
    when:
      event: push
  frontend:
    image: g3rv4/transifex-builder
    commands:
      - "mkdir -p app/frontend"
      - "cd Traducir.Web"
      - "cp -r /var/node_modules node_modules"
      - "npm run build"
      - "cp -r ./dist/* ../app/frontend/"
    when:
      event: push
  last:
    image: g3rv4/transifex-builder
    commands:
      - "ls"
      - "ls app/*"
    when:
      event: push