pipeline:
  build:
    image: g3rv4/transifex-builder
    when:
      branch: master
    commands:
      - "git clone git@github.com:g3rv4-docker/traducir.git output-image"
      - "rm -rf output-image/app/backend"
      - "rm -rf output-image/app/frontend"
      - "mkdir -p output-image/app/backend"
      - "mkdir -p output-image/app/frontend"

      - "cd Traducir.Api"
      - "dotnet publish -c Release -f netcoreapp2.0 -o ../output-image/app/backend"
      - "cd ../"
      
      - "cd Traducir.Web"
      - "npm install"
      - "npm run build"
      - "cp -r ./dist/* ../output-image/app/frontend/"
      - "cd ../"

      - "cd output-image"
      - "git add app"
      - "git commit -m \"Source update: ${DRONE_COMMIT_SHA} - ${DRONE_COMMIT_MESSAGE}\""
      - "git push"