pipeline:
  backend-master:
    image: g3rv4/transifex-builder
    commands:
      - "rm -rf /var/traducir-image/app/backend"
      - "mkdir -p /var/traducir-image/app/backend"

      - "cd Traducir.Api"
      - "dotnet publish -c Release -f netcoreapp2.0 -o /var/traducir-image/app/backend"
    volumes:
      - /home/gervasio/docker/traducir-image:/var/traducir-image
    when:
      event: push
      branch: master
  frontend-master:
    image: g3rv4/transifex-builder
    commands:
      - "rm -rf /var/traducir-image/app/frontend"
      - "mkdir -p /var/traducir-image/app/frontend"

      - "cd Traducir.Web"
      - "cp -r /var/node_modules node_modules"
      - "npm run build"
      - "cp -r ./dist/* /var/traducir-image/app/frontend/"
    volumes:
      - /home/gervasio/docker/traducir-image:/var/traducir-image
    when:
      event: push
      branch: master
  backend-pr:
    image: g3rv4/transifex-builder
    commands:
      - "cd Traducir.Api"
      - "dotnet publish -c Release -f netcoreapp2.0 -o /var/traducir-image/app/backend"
    when:
      event: pull_request
  frontend-pr:
    image: g3rv4/transifex-builder
    commands:
      - "cd Traducir.Web"
      - "cp -r /var/node_modules node_modules"
      - "npm run build"
    when:
      event: pull_request
  release-dev:
    image: g3rv4/docker
    commands:
      - "docker build -t g3rv4/traducir:dev /var/traducir-image"
      - "docker stop traducir_traducir_dev_1"
      - "docker rm -f traducir_traducir_dev_1"
      - "docker-compose -f /var/traducir/docker-compose.yml up -d"
      - "sleep 10"
      - "curl -X DELETE \"https://api.cloudflare.com/client/v4/zones/$${CLOUDFLARE_ZONE}/purge_cache\" -H \"X-Auth-Email: $${CLOUDFLARE_EMAIL}\" -H \"X-Auth-Key: $${CLOUDFLARE_KEY}\" -H \"Content-Type: application/json\" --data '{\"purge_everything\":true}'"
      - "docker exec traducir_traducir_dev_1 curl -i http://localhost:5000/app/api/admin/migrate"
    secrets: [cloudflare_zone, cloudflare_email, cloudflare_key]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/gervasio/docker/traducir-image:/var/traducir-image
      - /home/gervasio/docker/traducir:/var/traducir
    when:
      event: push
      branch: master
  release-prod:
    image: g3rv4/docker
    commands:
      - "docker build -t g3rv4/traducir /var/traducir-image"
      - "docker stop traducir_traducir_1"
      - "docker rm -f traducir_traducir_1"
      - "docker-compose -f /var/traducir/docker-compose.yml up -d"
      - "sleep 10"
      - "curl -X DELETE \"https://api.cloudflare.com/client/v4/zones/$${CLOUDFLARE_ZONE}/purge_cache\" -H \"X-Auth-Email: $${CLOUDFLARE_EMAIL}\" -H \"X-Auth-Key: $${CLOUDFLARE_KEY}\" -H \"Content-Type: application/json\" --data '{\"purge_everything\":true}'"
      - "docker exec traducir_traducir_1 curl -i http://localhost:5000/app/api/admin/migrate"
    secrets: [cloudflare_zone, cloudflare_email, cloudflare_key]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/gervasio/docker/traducir-image:/var/traducir-image
      - /home/gervasio/docker/traducir:/var/traducir
    when:
      event: deployment
      branch: master
