pipeline:
  backend:
    image: g3rv4/transifex-builder
    commands:
      - "cd Traducir.Api"
      - "dotnet publish -c Release -f netcoreapp2.0 -o ./app/backend"
  frontend:
    image: g3rv4/transifex-builder
    commands:
      - "cd Traducir.Web"
      - "cp -r /var/node_modules node_modules"
      - "npm run build"
      - "cp -r ./dist/* ./app/frontend/"
  last:
    image: g3rv4/transifex-builder
    commands:
      - "ls"
      - "ls app/*"
